# Rails.application.config.assets.precompile += %w( fancybox.png )
# Rails.application.config.assets.precompile += %w( blank.gif )
# Rails.application.config.assets.precompile += %w( fancybox-x.png )
# Rails.application.config.assets.precompile += %w( fancybox-y.png )
# Rails.application.config.assets.precompile += %w( fancy_title_over.png )
# Rails.application.config.assets.precompile += %w( fancy_close.png )