# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Playlist.create(name: "Beatles Influences Playlist")
Song.create(title:"I just don't understand (45)", artist:"Ann-Margret", year:1961, place:"Nashville, TN")
Song.create(title:"Anna (go to him)", artist:"Arthur Alexander", year:1962, place:"Muscle Shoals, AL")
Song.create(title:"Soldier of love", artist:"Arthur Alexander", year:1962, place:"Muscle Shoals, AL")
Song.create(title:"Where have you been?", artist:"Arthur Alexander", year:1962, place:"Muscle Shoals, AL")
Song.create(title:"You better move on (45)", artist:"Arthur Alexander", year:1962, place:"Muscle Shoals, AL")
Song.create(title:"Money (that's what I want)", artist:"Barrett Strong", year:1959, place:"Detroit, MI")
Song.create(title:"Flyin' saucers rock and roll (78)", artist:"Billy Lee Riley & the Little Green Men", year:1957, place:"Memphis, TN")
Song.create(title:"Do you wanna dance?", artist:"Bobby Freeman", year:1958, place:"San Francisco, CA")
Song.create(title:"Brown-eyed handsome man", artist:"Buddy Holly", year:1963, place:"Lubbock, TX")
Song.create(title:"Words of love (45)", artist:"Buddy Holly & the Crickets ", year:1957, place:"Lubbock, TX")
Song.create(title:"Everybody's trying to be my baby", artist:"Carl Perkins", year:1957, place:"Jackson, TN")
Song.create(title:"Matchbox (45)", artist:"Carl Perkins", year:1958, place:"Jackson, TN")
Song.create(title:"The Hippy Hippy shake", artist:"Chan Romero", year:1959, place:"Los Angeles, CA")
Song.create(title:"Little Queenie", artist:"Chuck Berry", year:1957, place:"Chicago, IL")
Song.create(title:"Rock and Roll music", artist:"Chuck Berry", year:1959, place:"Chicago, IL")
Song.create(title:"Hey little girl", artist:"Dee Clark", year:1959, place:"Chicago, IL")
Song.create(title:"Somethin' else (33)", artist:"Eddie Cochran", year:1959, place:"Los Angeles, CA")
Song.create(title:"Three steps to heaven (33)", artist:"Eddie Cochran", year:1960, place:"Los Angeles, CA")
Song.create(title:"Girl of my best friend (45)", artist:"Elvis Presley", year:1960, place:"Memphis, TN")
Song.create(title:"I'm ready", artist:"Fats Domino", year:1959, place:"New Orleans, LA")
Song.create(title:"Rocky road blues", artist:"Gene Vincent & the Blue Caps", year:1958, place:"Nashville,TN")
Song.create(title:"Rocket '88'", artist:"Jackie Brenston & his Delta Cats", year:1951, place:"Nashville,TN")
Song.create(title:"Handy man (45)", artist:"Jimmy Jones", year:1959, place:"New York City, NY")
Song.create(title:"Leave my kitten alone (45)", artist:"Johnny Preston", year:1960, place:"Houston, TX")
Song.create(title:"Bad boy", artist:"Larry Williams", year:1958, place:"New Orleans, LA")
Song.create(title:"Dizzy miss Lizzy", artist:"Larry Williams", year:1958, place:"New Orleans, LA")
Song.create(title:"Slow down (45)", artist:"Larry Williams", year:1959, place:"New Orleans, LA")
Song.create(title:"Ya ya", artist:"Lee Dorsey", year:1961, place:"New Orleans, LA")
Song.create(title:"A taste of honey", artist:"Lenny Welch", year:1962, place:"New York City, NY")
Song.create(title:"Keep your hands off my baby", artist:"Little Eva", year:1962, place:"Brooklyn, NY")
Song.create(title:"Long tall Sally", artist:"Little Richard", year:1957, place:"Macon, GA")
Song.create(title:"Lucille", artist:"Little Richard", year:1957, place:"Macon, GA")
Song.create(title:"Have you ever had the blues?", artist:"Lloyd Price", year:1959, place:"New Orleans, LA")
Song.create(title:"Don't you rock me Daddy-o", artist:"Lonnie Donegan & his Skiffle Group", year:1956, place:"London, England")
Song.create(title:"Jack o'diamonds (78)", artist:"Lonnie Donegan & his Skiffle Group", year:1958, place:"London, England")
Song.create(title:"Talkin' 'bout you", artist:"Ray Charles", year:1957, place:"New York, NY")
Song.create(title:"Some other guy (45)", artist:"Richie Barrett", year:1962, place:"New York, NY")
Song.create(title:"Red sails in the sunset (45)", artist:"Tab Hunter", year:1957, place:"Hollywood, CA")
Song.create(title:"Yakety yak", artist:"The Coasters", year:1958, place:"Los Angeles, CA")
Song.create(title:"Chains (45)", artist:"The Cookies", year:1962, place:"New York, NY")
Song.create(title:"Don't ever change", artist:"The Crickets", year:1962, place:"Lubbock, TX")
Song.create(title:"Come go with me", artist:"The Del-Vikings", year:1957, place:"Pittsburg, PA")
Song.create(title:"Bad boy", artist:"The Donays", year:1962, place:"Detroit, MI")
Song.create(title:"Devil in his heart", artist:"The Donays", year:1962, place:"Detroit, MI")
Song.create(title:"Just in case", artist:"The Everly Brothers", year:1960, place:"Detroit, MI")
Song.create(title:"Do-wah-diddy diddy (45)", artist:"The Exciters", year:1963, place:"Queens, NY")
Song.create(title:"Shout (pts.1 & 2) (45)", artist:"The Isley Brothers", year:1959, place:"New York, NY")
Song.create(title:"Twist and shout (45)", artist:"The Isley Brothers", year:1962, place:"New York, NY")
Song.create(title:"Please Mr. Postman", artist:"The Marvelettes", year:1961, place:"Detroit, MI")
Song.create(title:"Shop around (45)", artist:"The Miracles", year:1960, place:"Detroit, MI")
Song.create(title:"You've really got a hold on me", artist:"The Miracles", year:1962, place:"Detroit, MI")
Song.create(title:"I wish I could shimmy like my sister Kate (45)", artist:"The Olympics", year:1960, place:"Los Angeles, CA")
Song.create(title:"Boys (45)", artist:"The Shirelles", year:1960, place:"New York, NY")
Song.create(title:"Will you love me tomorrow (45)", artist:"The Shirelles", year:1960, place:"New York, NY")
Song.create(title:"Sheila (45)", artist:"Tommy Roe", year:1962, place:"Nashville, TN")
